import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto p-8">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Home
        </Link>

        <div className="prose prose-neutral dark:prose-invert max-w-none">
          <h1>Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>

          <h2>Agreement to Terms</h2>
          <p>
            By accessing and using Fextrio, you agree to be bound by these Terms of Service and all
            applicable laws and regulations. If you do not agree with any of these terms, you are
            prohibited from using this application.
          </p>

          <h2>Use License</h2>
          <p>
            Permission is granted to use Fextrio for personal or commercial vehicle trip management
            purposes. This license shall automatically terminate if you violate any of these
            restrictions.
          </p>

          <h2>User Responsibilities</h2>
          <p>You are responsible for:</p>
          <ul>
            <li>Maintaining the accuracy of the information you enter</li>
            <li>Keeping your account credentials secure</li>
            <li>Any activity that occurs under your account</li>
            <li>Complying with all applicable laws and regulations</li>
          </ul>

          <h2>Service Availability</h2>
          <p>
            We strive to provide continuous service availability, but we do not guarantee that the
            service will be uninterrupted or error-free. We reserve the right to modify, suspend, or
            discontinue the service at any time.
          </p>

          <h2>Data Accuracy</h2>
          <p>
            While we provide tools to manage and calculate your vehicle trip data, you are solely
            responsible for verifying the accuracy of all calculations and reports generated by the
            application.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            Fextrio shall not be liable for any indirect, incidental, special, consequential, or
            punitive damages resulting from your use or inability to use the service.
          </p>

          <h2>Modifications to Service</h2>
          <p>
            We reserve the right to modify or discontinue, temporarily or permanently, the service
            with or without notice. We shall not be liable to you or any third party for any
            modification, suspension, or discontinuance of the service.
          </p>

          <h2>Termination</h2>
          <p>
            We may terminate or suspend your access to the service immediately, without prior notice,
            for any reason, including breach of these Terms.
          </p>

          <h2>Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the service
            after changes constitutes acceptance of the modified terms.
          </p>

          <h2>Contact Information</h2>
          <p>
            For questions about these Terms of Service, please contact us through the application or
            at your designated support channel.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Terms;
